import { SiteContent } from "@/types/content";

export const defaultSiteContent: SiteContent = {
  brand: {
    wordmark: "UIC STUDIO",
    accentColor: "#c6f36b",
    contactEmail: "design@uic.studio",
    navItems: [
      { id: "nav-1", label: "Studio", href: "#studio" },
      { id: "nav-2", label: "Services", href: "#services" },
      { id: "nav-3", label: "NFC Cards", href: "#nfc" },
      { id: "nav-4", label: "Selected Work", href: "#work" },
      { id: "nav-5", label: "Process", href: "#process" },
      { id: "nav-6", label: "FAQ", href: "#faq" },
      { id: "nav-7", label: "Contact", href: "#contact" },
    ],
    socialLinks: [
      { id: "soc-1", platform: "X (Twitter)", label: "Twitter", url: "https://x.com" },
      { id: "soc-2", platform: "LinkedIn", label: "LinkedIn", url: "https://linkedin.com" },
      { id: "soc-3", platform: "Instagram", label: "Instagram", url: "https://instagram.com" },
      { id: "soc-4", platform: "GitHub", label: "GitHub", url: "https://github.com/vyshnavvijayan/uic-studio" },
    ],
  },
  seo: {
    title: "UIC Studio — Digital Identity & Aerospace NFC Experiences",
    description: "Unique Identity Creation: Bespoke digital portfolio websites, aerospace-grade NFC business cards, and high-impact web flagships engineered for modern leaders.",
    keywords: "digital identity, NFC business card, portfolio studio, luxury business cards, bespoke web design, Next.js portfolio, executive branding",
    ogImage: "/images/nfccard.webp",
    canonicalUrl: "https://uic.studio",
  },
  sectionOrder: [
    "hero",
    "studioIntro",
    "services",
    "nfcShowcase",
    "work",
    "process",
    "testimonials",
    "faq",
    "contact",
  ],
  sections: {
    hero: {
      id: "hero",
      enabled: true,
      headlineLine1: "Make your",
      headlineLine2: "presence felt.",
      subtitle: "Distinctive websites. Remarkable identities. Connections that start with a tap.",
      closingHeadline: "More than a first impression.",
      exploreText: "Explore the studio",
      posterUrl: "/images/heropage/0001.webp",
      totalFrames: 44,
      frameBasePath: "/images/heropage",
    },
    studioIntro: {
      id: "studioIntro",
      enabled: true,
      label: "Unique Identity Creation",
      title: "Digital presence elevated to architectural precision.",
      descriptionParagraphs: [
        "UIC Studio bridges physical substance and digital clarity. We architect high-performance portfolio platforms and manufacture aerospace-grade physical accessories that transmit your credentials in a single physical interaction.",
        "Every project is crafted without templates. We unite typographic restraint, sub-150 millisecond load profiles, and tactile materials to ensure you command attention in every room you enter."
      ],
      locations: "London × Geneva × Tokyo × Worldwide",
      stats: [
        { id: "st-1", value: "<140ms", label: "Edge Response", sublabel: "Global CDN distribution" },
        { id: "st-2", value: "Grade 5", label: "Titanium Alloy", sublabel: "Precision CNC milled" },
        { id: "st-3", value: "100%", label: "Bespoke Codebases", sublabel: "Zero generic site builders" },
        { id: "st-4", value: "Dynamic", label: "OTA NFC Profile", sublabel: "Instant cloud endpoint sync" },
      ],
    },
    services: {
      id: "services",
      enabled: true,
      label: "Studio Capabilities",
      title: "Disciplines built for distinguished brands.",
      subtitle: "End-to-end design and precision engineering tailored for executive leaders, founders, and creative directors.",
      items: [
        {
          id: "srv-1",
          title: "Personal Portfolio Websites",
          category: "Digital Identity",
          description: "Custom digital flagships constructed for founders and creative leaders. Engineered with editorial layouts, kinetic interactions, and fluid mobile ergonomics.",
          features: ["Editorial typography systems", "Motion-driven interaction design", "Responsive cross-device tuning", "Instant load performance"],
          icon: "Sparkles",
        },
        {
          id: "srv-2",
          title: "Business & Agency Flagships",
          category: "Web Platforms",
          description: "High-impact web presences that convey institutional authority and distinct positioning, converting elite clientele and institutional partners.",
          features: ["Conversion-focused architecture", "Interactive case study showcases", "Modern accessibility standards", "Global search indexing"],
          icon: "Layers",
        },
        {
          id: "srv-3",
          title: "Aerospace NFC Business Cards",
          category: "Physical Accessories",
          description: "Solid titanium and carbon composite cards equipped with high-speed microchips. Tap any smartphone to beam contact credentials and portfolio links instantly.",
          features: ["Laser-engraved titanium/steel", "Cloud dynamic destination manager", "Universal iOS and Android tap", "Encrypted coordinate data storage"],
          icon: "Cpu",
        },
        {
          id: "srv-4",
          title: "SEO & Performance Engineering",
          category: "Optimization",
          description: "Rigorous technical audits, Core Web Vitals perfection, structured semantic data, and crawl budget acceleration to place you at the peak of relevant searches.",
          features: ["Sub-150ms first-contentful paint", "JSON-LD schema structuring", "Deep OpenGraph integration", "Zero layout shift architecture"],
          icon: "Zap",
        },
        {
          id: "srv-5",
          title: "Custom Admin Dashboards & CMS",
          category: "Tooling",
          description: "Tailored management interfaces allowing clients to update section copy, project galleries, and profile endpoints without developer intervention.",
          features: ["Role-based access permissions", "Draft versus publish workflows", "Media asset optimization", "Real-time preview panels"],
          icon: "Sliders",
        },
        {
          id: "srv-6",
          title: "Bespoke Web Applications",
          category: "Engineering",
          description: "High-complexity web applications featuring real-time data flows, secure authentication, client portals, and custom cloud integrations.",
          features: ["Next.js App Router architecture", "Supabase Postgres backends", "Encrypted storage buckets", "Vercel edge execution"],
          icon: "Code",
        },
      ],
    },
    nfcShowcase: {
      id: "nfcShowcase",
      enabled: true,
      label: "Tactile Engineering",
      title: "Physical luxury meets instant digital connectivity.",
      subtitle: "Laser-etched aerospace metals, precision-weighted cores, and dynamic microchips configured to beam your identity with zero friction.",
      cards: [
        {
          id: "card-titanium",
          name: "Aerospace Titanium",
          material: "Grade 5 Titanium",
          color: "#18181b",
          accentColor: "#c6f36b",
          surfaceFinish: "Matte Bead-Blasted PVD",
          description: "Engineered from aerospace-grade alloy with deep laser raster engraving and diamond-chamfered edges. Lightweight yet practically indestructible.",
          badge: "Signature Standard",
          weight: "24.8g",
        },
        {
          id: "card-platinum",
          name: "Brushed Platinum Steel",
          material: "316L Surgical Alloy",
          color: "#27272a",
          accentColor: "#e4e4e7",
          surfaceFinish: "Directional Linear Brush",
          description: "Substantial hand feel with high-density surgical steel. Weighted for an unmistakable luxury impression in private boardroom introductions.",
          badge: "Executive Edition",
          weight: "28.5g",
        },
        {
          id: "card-gold",
          name: "24K Aurum Mirror",
          material: "Electroplated Brass Matrix",
          color: "#231e13",
          accentColor: "#f6cf65",
          surfaceFinish: "High-Gloss Mirror Polish",
          description: "Triple-plated with 24k gold over a solid brass core, paired with micro-fiber laser etching that reflects light from every vantage point.",
          badge: "Private Client",
          weight: "31.2g",
        },
        {
          id: "card-carbon",
          name: "Stealth Carbon Weave",
          material: "Toray 3K Pre-Preg Carbon",
          color: "#0f0f10",
          accentColor: "#00f0ff",
          surfaceFinish: "Satin Resin Matrix",
          description: "True motorsport-grade carbon fiber composite with visible woven texture, delivering featherweight handling with high structural rigidity.",
          badge: "Motorsport Spec",
          weight: "14.2g",
        },
      ],
    },
    work: {
      id: "work",
      enabled: true,
      label: "Selected Work",
      title: "A gallery of distinctive identities.",
      subtitle: "A curated collection of completed digital identity systems, physical NFC experiences, and editorial flagships.",
      projects: [
        {
          id: "proj-1",
          title: "Premium NFC Identity",
          category: "Physical NFC Experience",
          description: "Bespoke laser-etched titanium card paired with a dynamic vCard routing architecture for executive board members.",
          image: "/images/nfccard.webp",
          link: "#contact",
          isConcept: false,
          deliverables: ["Hardware Milling", "Dynamic OTA Router", "vCard Sync"],
          year: "2025",
        },
        {
          id: "proj-2",
          title: "Brand Identity System",
          category: "Visual Architecture",
          description: "Complete visual redesign, modular typographic hierarchy, and motion guidelines for a boutique private investment house.",
          image: "/images/Brand Identity System.webp",
          link: "#contact",
          isConcept: false,
          deliverables: ["Design System", "Editorial Rules", "Brand Guidelines"],
          year: "2025",
        },
        {
          id: "proj-3",
          title: "Digital Presence Launch",
          category: "Web Platform",
          description: "High-performance digital flagship featuring smooth frame-sequence transitions and sub-140ms response latency.",
          image: "/images/digital-launch2.webp",
          link: "#contact",
          isConcept: false,
          deliverables: ["Next.js App", "Tailwind Theme", "Edge CDN"],
          year: "2025",
        },
        {
          id: "proj-4",
          title: "Creator Profile Experience",
          category: "Personal Branding",
          description: "Interactive portfolio with custom audio-visual micro-interactions for a multi-disciplinary visual artist.",
          image: "/images/Creator Profile Experience.webp",
          link: "#contact",
          isConcept: true,
          deliverables: ["Interactive Canvas", "Media Archiving", "Custom Domain"],
          year: "2025",
        },
        {
          id: "proj-5",
          title: "Business Identity Package",
          category: "Brand + NFC Suite",
          description: "Cohesive corporate presence combining multi-user NFC card suites with a unified team directory dashboard.",
          image: "/images/Business Identity Package.webp",
          link: "#contact",
          isConcept: false,
          deliverables: ["Team NFC System", "Admin Panel", "Centralized vCard"],
          year: "2025",
        },
        {
          id: "proj-6",
          title: "Luxury Portfolio System",
          category: "Creative Showcase",
          description: "Architectural layout system with generous whitespace, horizontal image pan, and synchronized editorial captions.",
          image: "/images/Luxury Portfolio System.png",
          link: "#contact",
          isConcept: true,
          deliverables: ["Editorial Layout", "Bespoke CMS", "Typography Design"],
          year: "2024",
        },
      ],
    },
    process: {
      id: "process",
      enabled: true,
      label: "Methodology",
      title: "A deliberate, four-stage progression.",
      subtitle: "From conceptual strategy to laser manufacturing and edge deployment, our process ensures total cohesion.",
      steps: [
        {
          id: "step-1",
          stepNumber: "01",
          title: "Strategic Discovery",
          subtitle: "Brand Audit & Blueprinting",
          description: "We audit your existing presence, clarify your audience expectations, and define an architectural blueprint for both digital and physical touchpoints.",
          duration: "Phase 1 • Week 1",
        },
        {
          id: "step-2",
          stepNumber: "02",
          title: "Architectural Design",
          subtitle: "Editorial Craft & Prototyping",
          description: "We formulate unique typography pairings, layout grids, motion choreographies, and hardware material specifications tailored to your aesthetic.",
          duration: "Phase 2 • Weeks 2–3",
        },
        {
          id: "step-3",
          stepNumber: "03",
          title: "Precision Engineering",
          subtitle: "Next.js & Laser Milling",
          description: "We build your platform using Next.js with sub-150ms performance targets, while our workshop laser-etches and encodes your NFC credentials.",
          duration: "Phase 3 • Weeks 4–5",
        },
        {
          id: "step-4",
          stepNumber: "04",
          title: "Deployment & Commission",
          subtitle: "Global Edge & Handover",
          description: "Your platform launches onto global edge CDN servers with SSL and SEO indexing, accompanied by delivery of your custom boxed hardware card.",
          duration: "Phase 4 • Week 6",
        },
      ],
    },
    testimonials: {
      id: "testimonials",
      enabled: true,
      label: "Endorsements",
      title: "Voices from our private circle.",
      subtitle: "Verified reflections from executives, founders, and directors who carry UIC identities.",
      items: [
        {
          id: "test-1",
          author: "Marcus Sterling",
          role: "Managing Partner",
          company: "Aether Capital",
          avatarText: "MS",
          quote: "The combination of an editorial modular portfolio and custom titanium NFC cards makes a memorable impression in high-level private meetings. Absolute class.",
          approved: true,
        },
        {
          id: "test-2",
          author: "Evelyn Moreau",
          role: "Creative Director",
          company: "Maison de Couture",
          avatarText: "EM",
          quote: "The luxury whitespace, typographic attention, and fluid responsiveness of our portfolio is superb. It loads under 140ms on modern devices, representing our brand identity precisely.",
          approved: true,
        },
        {
          id: "test-3",
          author: "Jared Vance",
          role: "Founding Partner",
          company: "Vance & Holt Architecture",
          avatarText: "JV",
          quote: "Handing over a weighted steel card that instantly opens our architectural archive on the client's screen is a conversation starter every single time.",
          approved: true,
        },
      ],
    },
    faq: {
      id: "faq",
      enabled: true,
      label: "Inquiries & Specifics",
      title: "Frequently asked questions.",
      subtitle: "Clear answers regarding NFC hardware compatibility, production timelines, and platform capabilities.",
      items: [
        {
          id: "faq-1",
          question: "How does the NFC card connect to my digital portfolio?",
          answer: "Inside each titanium and composite card is an embedded NTAG microchip. When brought within 3cm of an iPhone or Android phone, the phone naturally detects the NFC signal and opens your designated URL or dynamic vCard profile immediately, with zero application required.",
          category: "Hardware",
        },
        {
          id: "faq-2",
          question: "Can I update my contact details or links without replacing the card?",
          answer: "Yes. All UIC cards are routed through our cloud endpoint manager. When your phone number, email, portfolio URL, or social links change, you simply update your profile in the CMS dashboard and your physical card immediately directs to the new information.",
          category: "Technology",
        },
        {
          id: "faq-3",
          question: "What materials and finishes are available for commissions?",
          answer: "Our core catalog includes Aerospace Grade 5 Titanium (Matte Bead-Blasted), 316L Surgical Steel (Brushed Platinum), 24K Gold Electroplated Brass, and Toray 3K Pre-Preg Carbon Fiber. We also accommodate custom finishes and bespoke dual-material combinations.",
          category: "Materials",
        },
        {
          id: "faq-4",
          question: "What is the typical production and delivery timeline?",
          answer: "A complete digital portfolio build and custom laser-engraved NFC card package typically requires 4 to 6 weeks from kickoff to deployment. Accelerated delivery schedules are available on inquiry for time-sensitive commitments.",
          category: "Process",
        },
        {
          id: "faq-5",
          question: "Can I bring my own custom domain or existing email service?",
          answer: "Absolutely. We configure custom domain routing (e.g., yourname.com) with automated SSL certificates, enterprise DNS routing, and email forwarding integration.",
          category: "Hosting",
        },
      ],
    },
    contact: {
      id: "contact",
      enabled: true,
      label: "Direct Engagement",
      title: "Initiate your commission.",
      subtitle: "Discuss a digital flagship, bespoke NFC suite, or identity redesign directly with our studio principals.",
      email: "design@uic.studio",
      secondaryEmail: "commissions@uic.studio",
      availabilityStatus: "Available for Q4 Commissions",
      responseTimeNotice: "Inquiries reviewed within one business day.",
    },
    footer: {
      id: "footer",
      enabled: true,
      wordmark: "UIC STUDIO",
      tagline: "Unique Identity Creation — Digital Flagships & Aerospace NFC Hardware.",
      copyrightText: "© 2026 UIC Studio. All rights reserved.",
      locationNotice: "London × Geneva × Tokyo • Worldwide Commission Handover",
    },
  },
};
